const sportsData = {
    categories: [
        {
            id: "musculation",
            name: "musculation_label",
            image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000",
            icon: "🏋️",
            color: "from-red-600 to-orange-500",
            sports: ["musculation", "bodybuilding", "crossfit", "circuit_training", "functional_training", "halterophilie", "powerlifting", "trx", "bootcamp", "hiit"]
        },
        {
            id: "cardio_endurance",
            name: "cardio_endurance_label",
            image: "https://images.unsplash.com/photo-1538805060514-97d9cc17730c?q=80&w=1000",
            icon: "🏃",
            color: "from-blue-600 to-cyan-500",
            sports: ["fitness_cardio", "running", "step_aerobic", "spinning", "rpm", "cardio_boxing", "jumping_fitness", "zumba_strong"]
        },
        {
            id: "fitness_danse",
            name: "fitness_danse_label",
            image: "https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?q=80&w=1000",
            icon: "💃",
            color: "from-purple-600 to-pink-500",
            sports: ["zumba", "dance_fitness", "afro_dance", "bokwa", "shbam", "bodyjam"]
        },
        {
            id: "souplesse_bien_etre",
            name: "souplesse_bien_etre_label",
            image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=1000",
            icon: "🧘",
            color: "from-green-600 to-teal-500",
            sports: ["yoga", "pilates", "stretching", "bodybalance", "gym_douce", "gym_posturale"]
        },
        {
            id: "full_body_gx",
            name: "full_body_gx_label",
            image: "https://images.unsplash.com/photo-1518611012118-2969c631002e?q=80&w=1000",
            icon: "💪",
            color: "from-yellow-600 to-orange-500",
            sports: ["bodypump", "bodyattack", "bodycombat", "cxworx", "total_body_workout", "full_body_training"]
        },
        {
            id: "modern_fitness",
            name: "modern_fitness_label",
            image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000",
            icon: "⚡",
            color: "from-indigo-600 to-blue-500",
            sports: ["calisthenics", "street_workout", "tabata", "functional_circuit", "booty_workout", "gym_suedoise"]
        },
        {
            id: "adaptive_seniors",
            name: "adaptive_seniors_label",
            image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=1000",
            icon: "🌿",
            color: "from-emerald-600 to-green-500",
            sports: ["adaptive_fitness", "wheelchair_training", "hand_cycling", "seated_workout", "chair_yoga", "seniors_fitness", "senior_cardio", "senior_strength", "low_impact", "rehabilitation_fitness"]
        }
    ],
    sports: {
        musculation: {
            name: "musculation_name",
            category_id: "musculation",
            description: "musculation_desc",
            benefits: "musculation_benefits",
            target: "musculation_target",
            goal: "musculation_goal",
            specs: { type: "individual", effort: "high", calories: "300-500", equipment: "dumbbells_machines", age: "16_plus" },
            image: "https://images.unsplash.com/photo-1581009146145-b5ef03a24b77?q=80&w=1000",
            youtube_id: "UppH3kckvd4",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        bodybuilding: {
            name: "bodybuilding_name",
            category_id: "musculation",
            description: "bodybuilding_desc",
            benefits: "bodybuilding_benefits",
            target: "bodybuilding_target",
            goal: "bodybuilding_goal",
            specs: { type: "individual", effort: "extreme", calories: "400-600", equipment: "full_gym", age: "18_plus" },
            image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000",
            youtube_id: "2O_rLQnlnlI",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        crossfit: {
            name: "crossfit_name",
            category_id: "musculation",
            description: "crossfit_desc",
            benefits: "crossfit_benefits",
            target: "crossfit_target",
            goal: "crossfit_goal",
            specs: { type: "group", effort: "extreme", calories: "500-900", equipment: "full_gym", age: "16_plus" },
            image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000",
            youtube_id: "SnJNFvO3JQI",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        circuit_training: {
            name: "circuit_training_name",
            category_id: "musculation",
            description: "circuit_desc",
            benefits: "circuit_benefits",
            target: "circuit_target",
            goal: "circuit_goal",
            specs: { type: "individual_group", effort: "high", calories: "400-600", equipment: "various", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?q=80&w=1000",
            youtube_id: "ml6cT4AZdqI",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        functional_training: {
            name: "functional_training_name",
            category_id: "musculation",
            description: "functional_desc",
            benefits: "functional_benefits",
            target: "functional_target",
            goal: "functional_goal",
            specs: { type: "individual", effort: "medium_high", calories: "350-550", equipment: "various", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000",
            youtube_id: "ml6cT4AZdqI",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        halterophilie: {
            name: "halterophilie_name",
            category_id: "musculation",
            description: "halterophilie_desc",
            benefits: "halterophilie_benefits",
            target: "halterophilie_target",
            goal: "halterophilie_goal",
            specs: { type: "individual", effort: "extreme", calories: "300-500", equipment: "barbell_plates", age: "16_plus" },
            image: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?q=80&w=1000",
            youtube_id: "UppH3kckvd4",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        powerlifting: {
            name: "powerlifting_name",
            category_id: "musculation",
            description: "powerlifting_desc",
            benefits: "powerlifting_benefits",
            target: "powerlifting_target",
            goal: "powerlifting_goal",
            specs: { type: "individual", effort: "extreme", calories: "300-500", equipment: "barbell_plates", age: "16_plus" },
            image: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?q=80&w=1000",
            youtube_id: "UppH3kckvd4",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        trx: {
            name: "trx_name",
            category_id: "musculation",
            description: "trx_desc",
            benefits: "trx_benefits",
            target: "trx_target",
            goal: "trx_goal",
            specs: { type: "individual_group", effort: "medium_high", calories: "300-500", equipment: "trx_straps", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?q=80&w=1000",
            youtube_id: "ml6cT4AZdqI",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        bootcamp: {
            name: "bootcamp_name",
            category_id: "musculation",
            description: "bootcamp_desc",
            benefits: "bootcamp_benefits",
            target: "bootcamp_target",
            goal: "bootcamp_goal",
            specs: { type: "group", effort: "extreme", calories: "500-800", equipment: "various", age: "16_plus" },
            image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000",
            youtube_id: "SnJNFvO3JQI",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        hiit: {
            name: "hiit_name",
            category_id: "musculation",
            description: "hiit_desc",
            benefits: "hiit_benefits",
            target: "hiit_target",
            goal: "hiit_goal",
            specs: { type: "individual_group", effort: "extreme", calories: "400-800", equipment: "none", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000",
            youtube_id: "ml6cT4AZdqI",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        // CARDIO & ENDURANCE
        fitness_cardio: {
            name: "fitness_cardio_name",
            category_id: "cardio_endurance",
            description: "fitness_cardio_desc",
            benefits: "fitness_cardio_benefits",
            target: "fitness_cardio_target",
            goal: "fitness_cardio_goal",
            specs: { type: "individual_group", effort: "high", calories: "400-600", equipment: "none", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1518611012118-2969c631002e?q=80&w=1000",
            youtube_id: "UBMk30rjy0o",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        running: {
            name: "running_name",
            category_id: "cardio_endurance",
            description: "running_desc",
            benefits: "running_benefits",
            target: "running_target",
            goal: "running_goal",
            specs: { type: "individual", effort: "very_high", calories: "600-900", equipment: "treadmill", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1538805060514-97d9cc17730c?q=80&w=1000",
            youtube_id: "kVnyY17VS9Y",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        step_aerobic: {
            name: "step_aerobic_name",
            category_id: "cardio_endurance",
            description: "step_desc",
            benefits: "step_benefits",
            target: "step_target",
            goal: "step_goal",
            specs: { type: "group", effort: "high", calories: "400-600", equipment: "step", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?q=80&w=1000",
            youtube_id: "UBMk30rjy0o",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        spinning: {
            name: "spinning_name",
            category_id: "cardio_endurance",
            description: "spinning_desc",
            benefits: "spinning_benefits",
            target: "spinning_target",
            goal: "spinning_goal",
            specs: { type: "group", effort: "very_high", calories: "400-600", equipment: "spin_bike", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1000",
            youtube_id: "wnRH0o0E9cc",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        rpm: {
            name: "rpm_name",
            category_id: "cardio_endurance",
            description: "spinning_desc",
            benefits: "spinning_benefits",
            target: "spinning_target",
            goal: "spinning_goal",
            specs: { type: "group", effort: "very_high", calories: "500-700", equipment: "spin_bike", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1000",
            youtube_id: "wnRH0o0E9cc",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        cardio_boxing: {
            name: "cardio_boxing_name",
            category_id: "cardio_endurance",
            description: "cardio_boxing_desc",
            benefits: "cardio_boxing_benefits",
            target: "cardio_boxing_target",
            goal: "cardio_boxing_goal",
            specs: { type: "group", effort: "very_high", calories: "500-700", equipment: "gloves", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1552072092-7f9b8d63efcb?q=80&w=1000",
            youtube_id: "TStxNSmIuFo",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        jumping_fitness: {
            name: "jumping_fitness_name",
            category_id: "cardio_endurance",
            description: "jumping_desc",
            benefits: "jumping_benefits",
            target: "jumping_target",
            goal: "jumping_goal",
            specs: { type: "group", effort: "high", calories: "400-600", equipment: "trampoline", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1518611012118-2969c631002e?q=80&w=1000",
            youtube_id: "UBMk30rjy0o",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        zumba_strong: {
            name: "zumba_strong_name",
            category_id: "cardio_endurance",
            description: "fitness_cardio_desc",
            benefits: "fitness_cardio_benefits",
            target: "fitness_cardio_target",
            goal: "fitness_cardio_goal",
            specs: { type: "group", effort: "very_high", calories: "500-700", equipment: "none", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?q=80&w=1000",
            youtube_id: "SkPZ6hyLTcg",
            video: "https://cdn.pixabay.com/vimeo/328943965/dance-22444.mp4",
            commercial_use: true
        },
        // DANCE FITNESS
        zumba: {
            name: "zumba_name",
            category_id: "fitness_danse",
            description: "fitness_cardio_desc",
            benefits: "fitness_cardio_benefits",
            target: "fitness_cardio_target",
            goal: "fitness_cardio_goal",
            specs: { type: "group", effort: "high", calories: "400-600", equipment: "none", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?q=80&w=1000",
            youtube_id: "SkPZ6hyLTcg",
            video: "https://cdn.pixabay.com/vimeo/328943965/dance-22444.mp4",
            commercial_use: true
        },
        dance_fitness: {
            name: "dance_fitness_name",
            category_id: "fitness_danse",
            description: "fitness_cardio_desc",
            benefits: "fitness_cardio_benefits",
            target: "fitness_cardio_target",
            goal: "fitness_cardio_goal",
            specs: { type: "group", effort: "high", calories: "350-550", equipment: "none", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?q=80&w=1000",
            youtube_id: "SkPZ6hyLTcg",
            video: "https://cdn.pixabay.com/vimeo/328943965/dance-22444.mp4",
            commercial_use: true
        },
        afro_dance: {
            name: "afro_dance_name",
            category_id: "fitness_danse",
            description: "fitness_cardio_desc",
            benefits: "fitness_cardio_benefits",
            target: "fitness_cardio_target",
            goal: "fitness_cardio_goal",
            specs: { type: "group", effort: "high", calories: "400-600", equipment: "none", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?q=80&w=1000",
            youtube_id: "SkPZ6hyLTcg",
            video: "https://cdn.pixabay.com/vimeo/328943965/dance-22444.mp4",
            commercial_use: true
        },
        bokwa: {
            name: "bokwa_name",
            category_id: "fitness_danse",
            description: "fitness_cardio_desc",
            benefits: "fitness_cardio_benefits",
            target: "fitness_cardio_target",
            goal: "fitness_cardio_goal",
            specs: { type: "group", effort: "high", calories: "500-800", equipment: "none", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?q=80&w=1000",
            youtube_id: "SkPZ6hyLTcg",
            video: "https://cdn.pixabay.com/vimeo/328943965/dance-22444.mp4",
            commercial_use: true
        },
        shbam: {
            name: "shbam_name",
            category_id: "fitness_danse",
            description: "fitness_cardio_desc",
            benefits: "fitness_cardio_benefits",
            target: "fitness_cardio_target",
            goal: "fitness_cardio_goal",
            specs: { type: "group", effort: "medium", calories: "400-500", equipment: "none", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?q=80&w=1000",
            youtube_id: "SkPZ6hyLTcg",
            video: "https://cdn.pixabay.com/vimeo/328943965/dance-22444.mp4",
            commercial_use: true
        },
        bodyjam: {
            name: "bodyjam_name",
            category_id: "fitness_danse",
            description: "fitness_cardio_desc",
            benefits: "fitness_cardio_benefits",
            target: "fitness_cardio_target",
            goal: "fitness_cardio_goal",
            specs: { type: "group", effort: "high", calories: "500-700", equipment: "none", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?q=80&w=1000",
            youtube_id: "SkPZ6hyLTcg",
            video: "https://cdn.pixabay.com/vimeo/328943965/dance-22444.mp4",
            commercial_use: true
        },
        // SOUPLESSE & BIEN-ÊTRE
        yoga: {
            name: "yoga_name",
            category_id: "souplesse_bien_etre",
            description: "yoga_desc",
            benefits: "yoga_benefits",
            target: "yoga_target",
            goal: "yoga_goal",
            specs: { type: "individual", effort: "low_medium", calories: "200-400", equipment: "yoga_mat", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=1000",
            youtube_id: "v7AYKMP6rOE",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        pilates: {
            name: "pilates_name",
            category_id: "souplesse_bien_etre",
            description: "pilates_desc",
            benefits: "pilates_benefits",
            target: "pilates_target",
            goal: "pilates_goal",
            specs: { type: "individual", effort: "medium", calories: "250-400", equipment: "yoga_mat", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1518611012118-2969c631002e?q=80&w=1000",
            youtube_id: "g-eLkSVo9gQ",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        stretching: {
            name: "stretching_name",
            category_id: "souplesse_bien_etre",
            description: "stretching_desc",
            benefits: "stretching_benefits",
            target: "stretching_target",
            goal: "stretching_goal",
            specs: { type: "individual", effort: "low", calories: "150-250", equipment: "yoga_mat", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1518611012118-2969c631002e?q=80&w=1000",
            youtube_id: "qULTwquOuT4",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        bodybalance: {
            name: "bodybalance_name",
            category_id: "souplesse_bien_etre",
            description: "bodybalance_desc",
            benefits: "bodybalance_benefits",
            target: "bodybalance_target",
            goal: "bodybalance_goal",
            specs: { type: "group", effort: "medium", calories: "300-400", equipment: "yoga_mat", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=1000",
            youtube_id: "v7AYKMP6rOE",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        gym_douce: {
            name: "gym_douce_name",
            category_id: "souplesse_bien_etre",
            description: "gym_douce_desc",
            benefits: "gym_douce_benefits",
            target: "gym_douce_target",
            goal: "gym_douce_goal",
            specs: { type: "individual_group", effort: "low", calories: "200-300", equipment: "none", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1518611012118-2969c631002e?q=80&w=1000",
            youtube_id: "qULTwquOuT4",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        gym_posturale: {
            name: "gym_posturale_name",
            category_id: "souplesse_bien_etre",
            description: "gym_posturale_desc",
            benefits: "gym_posturale_benefits",
            target: "gym_posturale_target",
            goal: "gym_posturale_goal",
            specs: { type: "individual_group", effort: "low_medium", calories: "200-300", equipment: "none", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1518611012118-2969c631002e?q=80&w=1000",
            youtube_id: "qULTwquOuT4",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        // FULL BODY GX
        bodypump: {
            name: "bodypump_name",
            category_id: "full_body_gx",
            description: "bodypump_desc",
            benefits: "bodypump_benefits",
            target: "bodypump_target",
            goal: "bodypump_goal",
            specs: { type: "group", effort: "high", calories: "500-600", equipment: "barbell_plates", age: "16_plus" },
            image: "https://images.unsplash.com/photo-1518611012118-2969c631002e?q=80&w=1000",
            youtube_id: "UppH3kckvd4",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        bodyattack: {
            name: "bodyattack_name",
            category_id: "full_body_gx",
            description: "bodyattack_desc",
            benefits: "bodyattack_benefits",
            target: "bodyattack_target",
            goal: "bodyattack_goal",
            specs: { type: "group", effort: "extreme", calories: "700-800", equipment: "none", age: "16_plus" },
            image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000",
            youtube_id: "UBMk30rjy0o",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        bodycombat: {
            name: "bodycombat_name",
            category_id: "full_body_gx",
            description: "bodycombat_desc",
            benefits: "bodycombat_benefits",
            target: "bodycombat_target",
            goal: "bodycombat_goal",
            specs: { type: "group", effort: "very_high", calories: "700-750", equipment: "none", age: "16_plus" },
            image: "https://images.unsplash.com/photo-1552072092-7f9b8d63efcb?q=80&w=1000",
            youtube_id: "TStxNSmIuFo",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        cxworx: {
            name: "cxworx_name",
            category_id: "full_body_gx",
            description: "cxworx_desc",
            benefits: "cxworx_benefits",
            target: "cxworx_target",
            goal: "cxworx_goal",
            specs: { type: "group", effort: "medium_high", calories: "300-400", equipment: "tube_plates", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?q=80&w=1000",
            youtube_id: "ml6cT4AZdqI",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        total_body_workout: {
            name: "total_body_workout_name",
            category_id: "full_body_gx",
            description: "total_body_desc",
            benefits: "total_body_benefits",
            target: "total_body_target",
            goal: "total_body_goal",
            specs: { type: "group", effort: "high", calories: "500-700", equipment: "various", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1518611012118-2969c631002e?q=80&w=1000",
            youtube_id: "UBMk30rjy0o",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        full_body_training: {
            name: "full_body_training_name",
            category_id: "full_body_gx",
            description: "full_body_training_desc",
            benefits: "full_body_training_benefits",
            target: "full_body_training_target",
            goal: "full_body_training_goal",
            specs: { type: "group", effort: "high", calories: "500-700", equipment: "various", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1518611012118-2969c631002e?q=80&w=1000",
            youtube_id: "UBMk30rjy0o",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        // MODERN FITNESS
        calisthenics: {
            name: "calisthenics_name",
            category_id: "modern_fitness",
            description: "calisthenics_desc",
            benefits: "calisthenics_benefits",
            target: "calisthenics_target",
            goal: "calisthenics_goal",
            specs: { type: "individual", effort: "very_high", calories: "400-700", equipment: "pullup_bar", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000",
            youtube_id: "SnJNFvO3JQI",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        street_workout: {
            name: "street_workout_name",
            category_id: "modern_fitness",
            description: "street_workout_desc",
            benefits: "street_workout_benefits",
            target: "street_workout_target",
            goal: "street_workout_goal",
            specs: { type: "individual", effort: "extreme", calories: "500-800", equipment: "none", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000",
            youtube_id: "SnJNFvO3JQI",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        tabata: {
            name: "tabata_name",
            category_id: "modern_fitness",
            description: "tabata_desc",
            benefits: "tabata_benefits",
            target: "tabata_target",
            goal: "tabata_goal",
            specs: { type: "individual_group", effort: "extreme", calories: "400-600", equipment: "none", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000",
            youtube_id: "ml6cT4AZdqI",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        functional_circuit: {
            name: "functional_circuit_name",
            category_id: "modern_fitness",
            description: "functional_circuit_desc",
            benefits: "functional_circuit_benefits",
            target: "functional_circuit_target",
            goal: "functional_circuit_goal",
            specs: { type: "group", effort: "high", calories: "500-700", equipment: "various", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000",
            youtube_id: "ml6cT4AZdqI",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        booty_workout: {
            name: "booty_workout_name",
            category_id: "modern_fitness",
            description: "booty_desc",
            benefits: "booty_benefits",
            target: "booty_target",
            goal: "booty_goal",
            specs: { type: "individual_group", effort: "medium_high", calories: "300-500", equipment: "none", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?q=80&w=1000",
            youtube_id: "UBMk30rjy0o",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        gym_suedoise: {
            name: "gym_suedoise_name",
            category_id: "modern_fitness",
            description: "gym_suedoise_desc",
            benefits: "gym_suedoise_benefits",
            target: "gym_suedoise_target",
            goal: "gym_suedoise_goal",
            specs: { type: "group", effort: "medium", calories: "300-500", equipment: "none", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1518611012118-2969c631002e?q=80&w=1000",
            youtube_id: "ml6cT4AZdqI",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        // ADAPTIVE & SENIORS
        adaptive_fitness: {
            name: "adaptive_fitness_name",
            category_id: "adaptive_seniors",
            description: "adaptive_fitness_desc",
            benefits: "adaptive_fitness_benefits",
            target: "adaptive_fitness_target",
            goal: "adaptive_fitness_goal",
            specs: { type: "individual", effort: "low_medium", calories: "150-300", equipment: "various", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=1000",
            youtube_id: "qULTwquOuT4",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        wheelchair_training: {
            name: "wheelchair_training_name",
            category_id: "adaptive_seniors",
            description: "wheelchair_training_desc",
            benefits: "wheelchair_training_benefits",
            target: "wheelchair_training_target",
            goal: "wheelchair_training_goal",
            specs: { type: "individual", effort: "medium", calories: "200-400", equipment: "wheelchair_accessible", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1581009146145-b5ef03a24b77?q=80&w=1000",
            youtube_id: "qULTwquOuT4",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        hand_cycling: {
            name: "hand_cycling_name",
            category_id: "adaptive_seniors",
            description: "hand_cycling_desc",
            benefits: "hand_cycling_benefits",
            target: "hand_cycling_target",
            goal: "hand_cycling_goal",
            specs: { type: "individual", effort: "medium_high", calories: "300-500", equipment: "hand_cycle", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=1000",
            youtube_id: "wnRH0o0E9cc",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        seated_workout: {
            name: "seated_workout_name",
            category_id: "adaptive_seniors",
            description: "seated_workout_desc",
            benefits: "seated_workout_benefits",
            target: "seated_workout_target",
            goal: "seated_workout_goal",
            specs: { type: "individual_group", effort: "low", calories: "100-200", equipment: "chair", age: "seniors_disabled" },
            image: "https://images.unsplash.com/photo-1518611012118-2969c631002e?q=80&w=1000",
            youtube_id: "qULTwquOuT4",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        chair_yoga: {
            name: "chair_yoga_name",
            category_id: "adaptive_seniors",
            description: "chair_yoga_desc",
            benefits: "chair_yoga_benefits",
            target: "chair_yoga_target",
            goal: "chair_yoga_goal",
            specs: { type: "group", effort: "low", calories: "100-150", equipment: "chair", age: "seniors_disabled" },
            image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=1000",
            youtube_id: "v7AYKMP6rOE",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        seniors_fitness: {
            name: "seniors_fitness_name",
            category_id: "adaptive_seniors",
            description: "seniors_fitness_desc",
            benefits: "seniors_fitness_benefits",
            target: "seniors_fitness_target",
            goal: "seniors_fitness_goal",
            specs: { type: "group", effort: "low_medium", calories: "200-300", equipment: "none", age: "seniors" },
            image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=1000",
            youtube_id: "qULTwquOuT4",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        senior_cardio: {
            name: "senior_cardio_name",
            category_id: "adaptive_seniors",
            description: "senior_cardio_desc",
            benefits: "senior_cardio_benefits",
            target: "senior_cardio_target",
            goal: "senior_cardio_goal",
            specs: { type: "group", effort: "medium", calories: "250-400", equipment: "none", age: "seniors" },
            image: "https://images.unsplash.com/photo-1518611012118-2969c631002e?q=80&w=1000",
            youtube_id: "kVnyY17VS9Y",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        senior_strength: {
            name: "senior_strength_name",
            category_id: "adaptive_seniors",
            description: "senior_strength_desc",
            benefits: "senior_strength_benefits",
            target: "senior_strength_target",
            goal: "senior_strength_goal",
            specs: { type: "group", effort: "medium", calories: "200-350", equipment: "light_weights", age: "seniors" },
            image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000",
            youtube_id: "UppH3kckvd4",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        low_impact: {
            name: "low_impact_name",
            category_id: "adaptive_seniors",
            description: "low_impact_desc",
            benefits: "low_impact_benefits",
            target: "low_impact_target",
            goal: "low_impact_goal",
            specs: { type: "individual_group", effort: "low", calories: "150-250", equipment: "none", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1518611012118-2969c631002e?q=80&w=1000",
            youtube_id: "qULTwquOuT4",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        },
        rehabilitation_fitness: {
            name: "rehabilitation_fitness_name",
            category_id: "adaptive_seniors",
            description: "rehab_desc",
            benefits: "rehab_benefits",
            target: "rehab_target",
            goal: "rehab_goal",
            specs: { type: "individual", effort: "low", calories: "100-200", equipment: "physio_tools", age: "all_ages" },
            image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=1000",
            youtube_id: "qULTwquOuT4",
            video: "https://cdn.pixabay.com/vimeo/147230414/fitness-1358.mp4",
            commercial_use: true
        }
    },

    // Coaches with specific sport images
    coaches: [
        {
            id: "coach_sarah",
            name: "Sarah Johnson",
            specialty: "yoga",
            specialty_label: "Yoga Specialist",
            price: 15,
            rating: 4.9,
            reviews: 127,
            image: "https://images.unsplash.com/photo-1567013127542-490d757e51fc?q=80&w=1000",
            bio: "Certified yoga instructor with 8 years of experience. Specializes in Hatha and Vinyasa yoga."
        },
        {
            id: "coach_mike",
            name: "Mike Ross",
            specialty: "musculation",
            specialty_label: "Strength & Conditioning",
            price: 20,
            rating: 4.8,
            reviews: 89,
            image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000",
            bio: "Former professional athlete. Expert in strength training and body composition."
        },
        {
            id: "coach_emma",
            name: "Emma Wilson",
            specialty: "hiit",
            specialty_label: "HIIT & Cardio Trainer",
            price: 12,
            rating: 4.7,
            reviews: 203,
            image: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?q=80&w=1000",
            bio: "Energetic HIIT coach specializing in high-intensity interval training and functional fitness."
        },
        {
            id: "coach_alex",
            name: "Alex Chen",
            specialty: "crossfit",
            specialty_label: "CrossFit Coach",
            price: 18,
            rating: 4.9,
            reviews: 156,
            image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?q=80&w=1000",
            bio: "CrossFit Level 2 certified trainer. Expert in Olympic lifting and functional movements."
        },
        {
            id: "coach_maria",
            name: "Maria Silva",
            specialty: "zumba",
            specialty_label: "Dance & Zumba Instructor",
            price: 10,
            rating: 4.8,
            reviews: 312,
            image: "https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?q=80&w=1000",
            bio: "Passionate Zumba instructor bringing energy and joy to every session."
        },
        {
            id: "coach_david",
            name: "David Okafor",
            specialty: "calisthenics",
            specialty_label: "Calisthenics & Street Workout",
            price: 14,
            rating: 4.6,
            reviews: 78,
            image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000",
            bio: "Street workout champion. Master of bodyweight training and calisthenics progressions."
        }
    ],

    // Marketplace products with sport-specific images
    products: [
        {
            id: "yoga_mat_pro",
            name: "Premium Yoga Mat",
            name_key: "premium_yoga_mat",
            price: 50,
            category: "yoga",
            image: "https://images.unsplash.com/photo-1517594422361-5eeb8ae275a9?q=80&w=1000",
            rating: 4.8,
            reviews: 234
        },
        {
            id: "dumbbells_adj",
            name: "Adjustable Dumbbells",
            name_key: "adjustable_dumbbells",
            price: 120,
            category: "musculation",
            image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=1000",
            rating: 4.9,
            reviews: 189
        },
        {
            id: "pi_watch",
            name: "Pi Smart Watch",
            name_key: "pi_smart_watch",
            price: 200,
            category: "tech",
            image: "https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?q=80&w=1000",
            rating: 4.7,
            reviews: 98
        },
        {
            id: "shoes_perf",
            name: "Performance Shoes",
            name_key: "performance_shoes",
            price: 85,
            category: "running",
            image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000",
            rating: 4.6,
            reviews: 445
        },
        {
            id: "resistance_bands",
            name: "Resistance Bands Set",
            name_key: "resistance_bands",
            price: 25,
            category: "fitness",
            image: "https://images.unsplash.com/photo-1598289431512-b97b0917affc?q=80&w=1000",
            rating: 4.8,
            reviews: 567
        },
        {
            id: "kettlebell",
            name: "Kettlebell 16kg",
            name_key: "kettlebell",
            price: 45,
            category: "musculation",
            image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=1000",
            rating: 4.7,
            reviews: 123
        },
        {
            id: "foam_roller",
            name: "Foam Roller Pro",
            name_key: "foam_roller",
            price: 30,
            category: "recovery",
            image: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000",
            rating: 4.5,
            reviews: 289
        },
        {
            id: "jump_rope",
            name: "Speed Jump Rope",
            name_key: "jump_rope",
            price: 15,
            category: "cardio",
            image: "https://images.unsplash.com/photo-1518611012118-2969c631002e?q=80&w=1000",
            rating: 4.6,
            reviews: 378
        }
    ]
};

window.sportsData = sportsData;
